fail if we can't get latest sbt version

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -91,9 +91,10 @@ jobs:
       run: |
         SBT_VERSION=$(
           curl -s curl -L https://github.com/sbt/sbt/releases |
-          grep -i -w 'sbt-[0-9]*\.[0-9]*\.[0-9]*\.tgz' -o |
-          grep -i -w '[0-9]*\.[0-9]*\.[0-9]*' -o |
+          grep -i -w -o '>[0-9]*\.[0-9]*\.[0-9]*</a>' |
+          grep -i -w -o '[0-9]*\.[0-9]*\.[0-9]*' |
           sort -V | tail -n 1)
+        [[ -z "$SBT_VERSION" ]] && { echo "Failed to get latest sbt version" ; exit 1; }
         echo ::set-output name=VERSION::$SBT_VERSION
     - name: Create docker tag
       id: create_docker_tag
